### ISSUE TITLE
logging have incorrect log levels

### ISSUE THREAD

**Issue by XCVYN6UGT85JywuH** [MythicMeta/MythicContainer#5]
When we make LogWarning, logr level is set to -1.
```
func LogWarning(message string, messages ...interface{}) {
	if pc, _, line, ok := runtime.Caller(1); ok {
                // here
		logger.V(-1).Info(message, append([]interface{}{"func", runtime.FuncForPC(pc).Name(), "line", line}, messages...)...)
	} else {
		logger.V(-1).Info(message, messages...)
	}
}
```

If we look at implementation of V method, we can see that it drops all negative values to zero. 
```
// V returns a new Logger instance for a specific verbosity level, relative to
// this Logger.  In other words, V-levels are additive.  A higher verbosity
// level means a log message is less important.  Negative V-levels are treated
// as 0.
func (l Logger) V(level int) Logger {
	if l.sink == nil {
		return l
	}
	if level < 0 {
		level = 0
	}
	l.level += level
	return l
}
```

So, when we set log level to Debug it actually being set to Info level. It doesn't make sense. Because by default mythic config has Warning log level, and we can't see any warning messages because of this.

**Comment by its-a-feature** [comment]
Good catch! zerolog and logr were working against each other - they tracked verbosity levels in opposite directions. I removed logr and stuck with just zerolog in the lates 1.3.11 release. If you could use that one and let me know if that addresses everything you were looking for
